# Generated by Django 5.1 on 2024-10-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApps1', '0005_employees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentModel',
        ),
        migrations.DeleteModel(
            name='TeacherModel',
        ),
        migrations.CreateModel(
            name='ProxyEmployees1',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('MyApps1.employees',),
        ),
        migrations.CreateModel(
            name='ProxyEmployees2',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('MyApps1.employees',),
        ),
    ]
